import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import Image from 'next/image'
import logo from '../../public/logo.svg'
import bg from '../../public/bg.svg'
import './globals.css'
import Navbar from '../components/navbar'
import About from '../components/about'
import Footer from '../components/footer'
import Contact from '../components/contact'
import Members from '../components/members'
import Gallery from '../components/gallery'
import Activity from '../components/activity'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Home Page',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel='icon' href='../../public/logo.svg' />
      </head>
      <body className={montserrat.className}>
        <Navbar />
        <div className='absolute w-full -z-10 overflow-hidden'>
          <Image src={bg} alt='image' className='w-full h-[1200px] lg:h-[1000px] object-cover' ></Image>
        </div>
        <About />
        <Activity />
        <Members />
        <Gallery />
        <Contact />
        <Footer />

        {children}
      </body>
    </html>
  )
}
