import type { Metadata } from 'next'
import { Inter, Montserrat } from 'next/font/google'
import './globals.css'
import Navbar from '../components/navbar'
import About from '../components/about'
import Footer from '../components/footer'
import Members from '../components/members'
import Gallery from '../components/gallery'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Navbar />
        <About />
        <Members />
        <Gallery />
        <Footer />

        {children}
      </body>
    </html>
  )
}
